# Generated by Django 2.1.2 on 2019-07-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentaccount',
            name='agent_name',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
