# Generated by Django 2.1.2 on 2019-07-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_agentaccount_agent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentaccount',
            name='pass_phrase',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
