# Generated by Django 2.1.2 on 2019-07-23 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_agentaccount_pass_phrase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentaccount',
            name='agent_name',
        ),
        migrations.RemoveField(
            model_name='agentaccount',
            name='pass_phrase',
        ),
    ]
