# Generated by Django 2.1.2 on 2019-07-22 15:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transport', '0006_auto_20190722_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateMachine',
            fields=[
                ('id', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('last_access', models.DateTimeField(auto_now=True)),
                ('context', django.contrib.postgres.fields.jsonb.JSONField()),
                ('transport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transport.TransportDescriptor')),
            ],
        ),
    ]
