# Generated by Django 2.1.2 on 2019-07-23 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state_machines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statemachine',
            name='transport',
        ),
    ]
