# Generated by Django 2.1.2 on 2019-07-23 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0008_endpoint'),
        ('state_machines', '0002_remove_statemachine_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='statemachine',
            name='endpoint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_machines', to='transport.Endpoint'),
        ),
    ]
