# Generated by Django 2.1.2 on 2019-07-23 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state_machines', '0003_statemachine_endpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statemachine',
            name='endpoint',
        ),
    ]
