# Generated by Django 2.1.2 on 2019-07-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state_machines', '0004_remove_statemachine_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='statemachine',
            name='endpoint_uid',
            field=models.CharField(db_index=True, max_length=2083, null=True),
        ),
    ]
