# Generated by Django 2.1.2 on 2019-07-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvokedStateMachine',
            fields=[
                ('machine_id', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('machine_class_name', models.CharField(max_length=512)),
            ],
        ),
    ]
