# Generated by Django 2.1.2 on 2019-07-25 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvokedStateMachine',
            new_name='StartedStateMachine',
        ),
    ]
