# Generated by Django 2.1.11 on 2020-03-31 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190725_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredDef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cred_def_id', models.CharField(max_length=128, unique=True)),
                ('body', models.TextField()),
            ],
        ),
    ]
