# Generated by Django 2.1.11 on 2020-03-31 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_creddef'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuerSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_id', models.CharField(max_length=128, unique=True)),
                ('body', models.TextField()),
            ],
        ),
    ]
