# Generated by Django 2.1.2 on 2019-07-24 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='status',
        ),
    ]
