# Generated by Django 2.1.2 on 2019-07-24 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_wallet_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
