# Generated by Django 2.1.2 on 2019-10-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_schemadefinition'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemadefinition',
            name='schema_id',
            field=models.CharField(max_length=512, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='schemadefinition',
            name='json',
            field=models.CharField(db_index=True, max_length=2056),
        ),
    ]
