# Generated by Django 2.1.2 on 2019-10-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20191015_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemadefinition',
            name='did',
            field=models.CharField(db_index=True, max_length=512, null=True),
        ),
    ]
