# Generated by Django 2.1.2 on 2019-10-15 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_schemadefinition_did'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemadefinition',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Wallet'),
        ),
    ]
