# Generated by Django 2.1.2 on 2019-10-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_schemadefinition_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cred_def_id', models.CharField(max_length=1024)),
                ('cred_def_json', models.CharField(max_length=10240)),
            ],
        ),
    ]
