# Generated by Django 2.1.2 on 2019-10-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20191016_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentialdefinition',
            name='cred_def_id',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
