# Generated by Django 2.1.2 on 2019-10-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20191016_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialdefinition',
            name='cred_def_request',
            field=models.CharField(db_index=True, max_length=10240, null=True),
        ),
    ]
