# Generated by Django 2.1.2 on 2019-10-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_credentialdefinition_cred_def_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentialdefinition',
            name='cred_def_json',
            field=models.CharField(db_index=True, max_length=10240),
        ),
    ]
