# Generated by Django 2.1.2 on 2019-10-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20191016_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentialdefinition',
            name='cred_def_json',
            field=models.CharField(db_index=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='credentialdefinition',
            name='cred_def_request',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
    ]
