# Generated by Django 2.1.2 on 2019-10-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20191016_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentialdefinition',
            name='cred_def_json',
            field=models.CharField(max_length=10240),
        ),
        migrations.AlterField(
            model_name='credentialdefinition',
            name='cred_def_request',
            field=models.CharField(max_length=10240, null=True),
        ),
    ]
