# Generated by Django 2.1.2 on 2019-10-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20191016_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialdefinition',
            name='schema_id',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
    ]
