# Generated by Django 2.1.2 on 2019-10-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_credentialdefinition_schema_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentialdefinition',
            name='cred_def_json',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='credentialdefinition',
            name='cred_def_request',
            field=models.TextField(null=True),
        ),
    ]
