# Generated by Django 2.1.2 on 2019-07-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportdescriptor',
            name='channel_name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
