# Generated by Django 2.1.2 on 2019-07-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_transportdescriptor_channel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportdescriptor',
            name='channel_name',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
