# Generated by Django 2.1.2 on 2019-07-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_auto_20190721_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportdescriptor',
            name='last_access',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='transportdescriptor',
            name='nonce',
            field=models.CharField(db_index=True, default='', max_length=128),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='transportdescriptor',
            name='channel_name',
        ),
        migrations.AlterUniqueTogether(
            name='transportdescriptor',
            unique_together={('entrypoint', 'nonce')},
        ),
    ]
