# Generated by Django 2.1.2 on 2019-07-22 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_entrypointdescriptor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportdescriptor',
            name='entrypoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nonces', to='transport.EntrypointDescriptor'),
        ),
    ]
