# Generated by Django 2.1.2 on 2019-08-23 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_wallet_endpoint'),
        ('transport', '0008_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='api.Wallet'),
        ),
    ]
