# Generated by Django 2.1.2 on 2019-08-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0009_endpoint_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
