# Generated by Django 2.1.2 on 2019-08-23 20:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0010_endpoint_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_string', models.CharField(max_length=1024)),
                ('invite_message', django.contrib.postgres.fields.jsonb.JSONField()),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='transport.Endpoint')),
            ],
        ),
    ]
