# Generated by Django 2.1.2 on 2019-08-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0011_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='feature',
            field=models.CharField(max_length=56, null=True),
        ),
    ]
