# Generated by Django 2.1.2 on 2019-08-23 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0012_invitation_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='invite_message',
        ),
    ]
