# Generated by Django 2.1.2 on 2019-08-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0013_remove_invitation_invite_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='connection_key',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
